### ISSUE TITLE
new error..?

### ISSUE THREAD

**Issue by dispaqi** [FuckingToasters/discord-group-spammer#5]
`Exception in thread Thread-2 (sendreq):
Exception in thread Traceback (most recent call last):
Exception in thread Exception in thread Thread-1 (sendreq)Thread-3 (sendreq)Exception in thread Exception in thread Exception in thread Thread-4 (sendreq)Thread-6 (sendreq)Thread-5 (sendreq):
Thread-7 (sendreq)Exception in thread :
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
:
Thread-10 (sendreq)Traceback (most recent call last):
Exception in thread :
:
Traceback (most recent call last):
Thread-8 (sendreq)Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Traceback (most recent call last):
:
Traceback (most recent call last):
:
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Exception in thread     :
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
Thread-9 (sendreq)Traceback (most recent call last):
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()        Traceback (most recent call last):
    :
self.run()  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()Traceback (most recent call last):
Traceback (most recent call last):

      File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
self.run()  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
self.run()  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run

      File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner

  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner

          File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
      File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
self.run()            self.run()
self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)self.run()
self._target(*self._args, **self._kwargs)    self.run()

self.run()  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run

  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run

  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq

      File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
          File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq
self._target(*self._args, **self._kwargs)  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq
            self._target(*self._args, **self._kwargs)already_checked = open('log.txt', mode='r')self._target(*self._args, **self._kwargs)  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run

self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq

already_checked = open('log.txt', mode='r')  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq
  File "C:\Users\Shadow\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq

FileNotFoundError
already_checked = open('log.txt', mode='r')    FileNotFoundError: self._target(*self._args, **self._kwargs)    self._target(*self._args, **self._kwargs)          File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq
  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq

: [Errno 2] No such file or directory: 'log.txt'
already_checked = open('log.txt', mode='r')already_checked = open('log.txt', mode='r')[Errno 2] No such file or directory: 'log.txt'

  File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq
FileNotFoundError
    already_checked = open('log.txt', mode='r')FileNotFoundError: already_checked = open('log.txt', mode='r')already_checked = open('log.txt', mode='r')    [Errno 2] No such file or directory: 'log.txt'

: FileNotFoundError
already_checked = open('log.txt', mode='r')FileNotFoundError: FileNotFoundError
[Errno 2] No such file or directory: 'log.txt'[Errno 2] No such file or directory: 'log.txt': FileNotFoundError

FileNotFoundError: [Errno 2] No such file or directory: 'log.txt':   File "C:\Users\Shadow\Downloads\discord-group-spammer-main\discord-group-spammer-main\all_together.py", line 129, in sendreq

[Errno 2] No such file or directory: 'log.txt':
    [Errno 2] No such file or directory: 'log.txt'[Errno 2] No such file or directory: 'log.txt'

already_checked = open('log.txt', mode='r')
FileNotFoundError: [Errno 2] No such file or directory: 'log.txt'`

lol sorry about so many issues idk whats going on
It was working fine but now i cant add people to groups anymore

i can still make groups

**Comment by FuckingToasters** [comment]
This means that the file log.txt do not exist but it exist in the repo so you should create it i also will add that is t create the file of not exist tomorrow. I also will add more stuff tomorrow but now i go to bed.

**Comment by dispaqi** [comment]
alright gn lol

**Comment by dispaqi** [comment]
D:\Files\Tools\Discord\discord group spammer\discord-group-spammer-main (1)\discord-group-spammer-main
is where i have the log.txt file, it is there

**Comment by FuckingToasters** [comment]
> D:\Files\Tools\Discord\discord group spammer\discord-group-spammer-main (1)\discord-group-spammer-main is where i have the log.txt file, it is there

It is weird that you have multiplie subfolders. python looks in the folder where you ran the script so if the file is in D:/Group-spammer and you ran the all_together file in another location it will look there. i think it is better to copy all files after redownloading it and pasting them in a folder you created,

**Comment by dispaqi** [comment]
i have done what you said and copied all the files into C:\Users\kai\Downloads\dds, i also changed the log.txt to r+
it seems to have fixed the log.txt error but now displays this
`  File "C:\Users\kai\Downloads\dds\all_together.py", line 136, in sendreq
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kai\Downloads\dds\all_together.py", line 136, in sendreq
    self._target(*self._args, **self._kwargs)
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
    shit = open('group_id.txt')
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
  File "C:\Users\kai\Downloads\dds\all_together.py", line 136, in sendreq
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'
    shit = open('group_id.txt')
FileNotFoundError: [Errno 2] No such file or directory: 'group_id.txt'`

**Comment by dispaqi** [comment]
ok so it works on my other computer, ig u dont have to bother lol
thanks tho

**Comment by dispaqi** [comment]
a good feature would be remove a user from all groups though

**Comment by FuckingToasters** [comment]
well i now edited the file so it create missing files before using them what should avoid this isse so you might want to redownload it. removing users from all groups and fetching members from guild as well as sending messages to all guilds is already implemented in the current file. you might want to update it because i did many changes yesterday and today.
